@TaskManagementApi_HostAddress = http://localhost:5173

GET {{TaskManagementApi_HostAddress}}/api/tasks
Accept: application/json
###
POST {{TaskManagementApi_HostAddress}}/api/tasks
Accept: application/json

{
    "title": "Learn ASP.NET Core",
    "description": "Build Task Management API"
}
###